logger:
  level: INFO
ota:
  - platform: esphome
    password: changeme-otapw
    # password: ${ota_password}
  - platform: http_request
time:
  - platform: sntp
    id: sntp_time
wifi:
  ap:
    ssid: "${name} Fallback"
    password: "${device_id}-ap"
captive_portal:
web_server:
  version: 3
  port: 80
  include_internal: true

sensor:
  - platform: wifi_signal
    name: "${name} WiFi RSSI"
    update_interval: 60s

button:
  - platform: restart
    name: "${name} Restart"
  - platform: template
    name: "${name} Update Latest Release"
    on_press:
      - ota.http_request.flash:
          url: https://github.com/ben-gineering/esphome-test/releases/latest/download/esphome-test.ota.bin
          md5_url: https://github.com/ben-gineering/esphome-test/releases/latest/download/esphome-test.ota.md5
  - platform: template
    name: "${name} Update Develop-Latest"
    on_press:
      - ota.http_request.flash:
          url: https://github.com/ben-gineering/esphome-test/releases/download/develop-latest/esphome-test.ota.bin
          md5_url: https://github.com/ben-gineering/esphome-test/releases/download/develop-latest/esphome-test.ota.md5
