logger:
  level: INFO
ota:
  - platform: esphome
    password: changeme-otapw
    # password: ${ota_password}
time:
  - platform: sntp
    id: sntp_time
wifi:
  ap:
    ssid: "${name} Fallback"
    password: "${device_id}-ap"
captive_portal:
web_server:
  port: 80
  include_internal: true

sensor:
  - platform: wifi_signal
    name: "${name} WiFi RSSI"
    update_interval: 60s

button:
  - platform: restart
    name: "${name} Restart"
