logger:
  level: INFO

http_request:
  timeout: 90s
  follow_redirects: true
  redirect_limit: 5
  buffer_size_rx: 8192
  buffer_size_tx: 2048
  watchdog_timeout: 45s
ota:
  - platform: esphome
    password: changeme-otapw
    # password: ${ota_password}
  - platform: http_request
time:
  - platform: sntp
    id: sntp_time
wifi:
  ap:
    ssid: "${name} Fallback"
    password: "${device_id}-ap"
captive_portal:
web_server:
  version: 3
  port: 80
  include_internal: true

sensor:
  - platform: wifi_signal
    name: "${name} WiFi RSSI"
    update_interval: 60s
 
text_sensor:
  - platform: template
    name: "Firmware Version"
    icon: mdi:information-box
    entity_category: diagnostic
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };

button:

  - platform: restart
    name: "${name} Restart"
  - platform: template
    name: "${name} Update Latest Release"
    on_press:
      - ota.http_request.flash:
          url: https://github.com/ben-gineering/esphome-test/releases/latest/download/esphome-test.ota.bin
          md5_url: https://github.com/ben-gineering/esphome-test/releases/latest/download/esphome-test.ota.md5
  - platform: template
    name: "${name} Update Develop-Latest"
    on_press:
      - ota.http_request.flash:
          url: https://github.com/ben-gineering/esphome-test/releases/download/develop-latest/esphome-test.ota.bin
          md5_url: https://github.com/ben-gineering/esphome-test/releases/download/develop-latest/esphome-test.ota.md5
